# Generated by Django 5.2.7 on 2026-05-28 13:50

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import projectRepo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color_hex', models.CharField(default='#6B7280', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('azure_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('azure_tenant_id', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('team_lead', 'Team Lead'), ('senior_tech', 'Senior Technician'), ('technician', 'Technician'), ('developer', 'Developer'), ('viewer', 'Viewer (Read Only)')], default='viewer', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('article_type', models.CharField(choices=[('support', 'Support Resolution'), ('project', 'Project Implementation'), ('software', 'Software Guide'), ('general', 'General Knowledge')], db_index=True, default='support', max_length=20)),
                ('summary', models.TextField(blank=True, max_length=600)),
                ('content', models.TextField()),
                ('search_keywords', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'All Staff'), ('restricted', 'Senior Staff Only'), ('private', 'Author Only')], default='public', max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('review_notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('n/a', 'Not Applicable')], default='n/a', max_length=10)),
                ('affected_systems', models.CharField(blank=True, max_length=500)),
                ('error_codes', models.CharField(blank=True, max_length=300)),
                ('microsoft_products', models.CharField(blank=True, max_length=400)),
                ('resolution_type', models.CharField(blank=True, max_length=100)),
                ('time_to_resolve_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=150)),
                ('tech_stack', models.CharField(blank=True, max_length=500)),
                ('difficulty_level', models.CharField(blank=True, max_length=20)),
                ('estimated_duration', models.CharField(blank=True, max_length=100)),
                ('prerequisites', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('helpful_votes', models.PositiveIntegerField(default=0, editable=False)),
                ('not_helpful_votes', models.PositiveIntegerField(default=0, editable=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_articles', to=settings.AUTH_USER_MODEL)),
                ('related_articles', models.ManyToManyField(blank=True, to='projectRepo.article')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectRepo.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projectRepo.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projectRepo.article')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category_type', models.CharField(choices=[('support', 'Support Resolution'), ('project', 'Project Implementation'), ('software', 'Software Development'), ('general', 'General Knowledge')], default='general', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('color_hex', models.CharField(default='#2563EB', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projectRepo.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='projectRepo.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectRepo.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projectRepo.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('article_published', 'Article Published'), ('comment', 'New Comment'), ('review_request', 'Review Requested'), ('mention', 'You Were Mentioned'), ('article_updated', 'Article Updated'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectRepo.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('results_count', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='projectRepo.tag'),
        ),
        migrations.CreateModel(
            name='ArticleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('feedback_text', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectRepo.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'user'), name='unique_user_article_feedback')],
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('code_language', models.CharField(blank=True, default='bash', max_length=50)),
                ('warning', models.TextField(blank=True)),
                ('tip', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('article', models.ForeignKey(limit_choices_to={'article_type': 'project'}, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projectRepo.article')),
            ],
            options={
                'ordering': ['step_number'],
                'constraints': [models.UniqueConstraint(fields=('article', 'step_number'), name='unique_article_step_order')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'visibility'], name='projectRepo_status_6ce9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', 'status'], name='projectRepo_article_34cb4f_idx'),
        ),
    ]
