# Generated by Django 5.2.7 on 2026-05-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectRepo', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='original_name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_size_bytes',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size stored explicitly in bytes'),
            preserve_default=False,
        ),
    ]
