# Generated by Django 5.2.7 on 2026-05-31 21:50

import projectRepo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectRepo', '0003_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=projectRepo.models.article_attachment_path),
        ),
    ]
